package forms.validation;

import java.awt.Color;
import java.awt.Image;
import java.util.prefs.Preferences;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class SignIn extends javax.swing.JFrame {

    Preferences preferences;
    boolean rememberPreference;
    
    
    
    public SignIn() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.eye.setVisible(false);
        rememberme();
        startComponenColor();
    }
    
    public void rememberme(){
        preferences = Preferences.userNodeForPackage(this.getClass());
        rememberPreference = preferences.getBoolean("RememberMe", Boolean.valueOf(""));
        if (rememberPreference){
        txtusername.setText(preferences.get("username", ""));
        txtpassword.setText(preferences.get("password", ""));
        remember.setSelected(rememberPreference);
        txtpassword.setEchoChar('*');
        }
    }
    
    public void startComponenColor(){
        if(!txtusername.getText().equals("username") && !txtpassword.getText().equals("password")){
        txtusername.setForeground(Color.black);
        txtpassword.setForeground(Color.black);
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg11 = new source.bg1();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        person2 = new source.person();
        txtusername = new javax.swing.JTextField();
        layform1 = new javax.swing.JLabel();
        eye = new javax.swing.JLabel();
        eyeclosed = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        layform2 = new javax.swing.JLabel();
        remember = new javax.swing.JCheckBox();
        forgotpass = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        txtcreateacc = new javax.swing.JLabel();
        createacc = new javax.swing.JLabel();
        card = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        wallet1 = new source.wallet();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-CelenganKu - Sign In");
        setMinimumSize(new java.awt.Dimension(710, 706));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(113, 170, 139));
        jLabel1.setText("Sign In");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 130, -1));

        person2.setOpaque(false);

        javax.swing.GroupLayout person2Layout = new javax.swing.GroupLayout(person2);
        person2.setLayout(person2Layout);
        person2Layout.setHorizontalGroup(
            person2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        person2Layout.setVerticalGroup(
            person2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(person2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 153, 153));
        txtusername.setText("username");
        txtusername.setBorder(null);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 224, 430, 30));

        layform1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/form.png"))); // NOI18N
        jPanel2.add(layform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 220, -1, -1));

        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/eye.png"))); // NOI18N
        eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeMousePressed(evt);
            }
        });
        jPanel2.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 289, -1, 30));

        eyeclosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/eye-slashed.png"))); // NOI18N
        eyeclosed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeclosed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eyeclosedMousePressed(evt);
            }
        });
        jPanel2.add(eyeclosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 289, -1, 30));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(153, 153, 153));
        txtpassword.setText("password");
        txtpassword.setBorder(null);
        txtpassword.setEchoChar('\u0000');
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 289, 430, 30));

        layform2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/form.png"))); // NOI18N
        jPanel2.add(layform2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 285, -1, -1));

        remember.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        remember.setText("Remember me");
        remember.setBorder(null);
        remember.setMargin(new java.awt.Insets(1, 1, 1, 1));
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });
        jPanel2.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 150, 30));

        forgotpass.setBackground(new java.awt.Color(255, 255, 255));
        forgotpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        forgotpass.setText("Forgot Password");
        forgotpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(forgotpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 355, -1, -1));

        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/button.png"))); // NOI18N
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        jPanel2.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 435, -1, -1));

        txtcreateacc.setText("Not Registered?");
        jPanel2.add(txtcreateacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 510, -1, -1));

        createacc.setBackground(new java.awt.Color(255, 255, 255));
        createacc.setForeground(new java.awt.Color(0, 0, 255));
        createacc.setText("Create Account");
        createacc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(createacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 510, -1, -1));

        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/card.png"))); // NOI18N
        jPanel2.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        jPanel1.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CelenganKu");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Copyright © 2022 sandhyzidan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(wallet1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wallet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout bg11Layout = new javax.swing.GroupLayout(bg11);
        bg11.setLayout(bg11Layout);
        bg11Layout.setHorizontalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg11Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bg11Layout.setVerticalGroup(
            bg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg11Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        if (txtusername.getText().equals("username")) {
            txtusername.setText("");
            txtusername.setForeground(new Color(153, 153, 153));

        }
        ImageIcon image = new ImageIcon(getClass().getResource("/source/form-selected.png"));
        layform1.setIcon(image);
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        if (txtusername.getText().isBlank()) {
            txtusername.setText("username");
            txtusername.setForeground(new Color(153, 153, 153));

        }
        ImageIcon image = new ImageIcon(getClass().getResource("/source/form.png"));
        layform1.setIcon(image);
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        txtpassword.setEchoChar('*');
        if (txtpassword.getText().equals("")) {
            txtpassword.setEchoChar((char) 0);
            txtpassword.setText("password");
            txtpassword.setForeground(new Color(153, 153, 153));

        }
        ImageIcon image = new ImageIcon(getClass().getResource("/source/form.png"));
        layform2.setIcon(image);
    }//GEN-LAST:event_txtpasswordFocusLost

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        if (txtpassword.getText().equals("password")) {
            txtpassword.setText("");
            txtpassword.setForeground(new Color(153, 153, 153));
        }
        ImageIcon image = new ImageIcon(getClass().getResource("/source/form-selected.png"));
        layform2.setIcon(image);
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        if (eye.isVisible()){
         txtpassword.setEchoChar((char) 0);
        }
        else if(eyeclosed.isVisible()){
        txtpassword.setEchoChar('*');
        }
        
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void eyeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMousePressed
        // TODO add your handling code here:
        eyeclosed.setVisible(true);
        eye.setVisible(false);
        if (txtpassword.getText().equals("password")) {

        } else {
            txtpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_eyeMousePressed

    private void eyeclosedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeclosedMousePressed
        // TODO add your handling code here:
        eye.setVisible(true);
        eyeclosed.setVisible(false);
        if (txtpassword.getText().equals("password")) {

        } else {
            txtpassword.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_eyeclosedMousePressed

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberActionPerformed

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        // TODO add your handling code here:
        String username = txtusername.getText();
        String password = txtpassword.getText();
        
        if (remember.isSelected() && !rememberPreference){
            preferences.put("username", username);
            preferences.put("password", password);
            preferences.putBoolean("RememberMe", true);
        }else if (!remember.isSelected() && rememberPreference){
            preferences.put("username", "");
            preferences.put("password", "");
            preferences.putBoolean("RememberMe", false);
        }
        else{
        JOptionPane.showMessageDialog(null, "ERROR");
        }
    }//GEN-LAST:event_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private source.bg1 bg11;
    private javax.swing.JLabel button;
    private javax.swing.JLabel card;
    private javax.swing.JLabel createacc;
    private javax.swing.JLabel eye;
    private javax.swing.JLabel eyeclosed;
    private javax.swing.JLabel forgotpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel layform1;
    private javax.swing.JLabel layform2;
    private source.person person2;
    private javax.swing.JCheckBox remember;
    private javax.swing.JLabel txtcreateacc;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private source.wallet wallet1;
    // End of variables declaration//GEN-END:variables
}
